# C#:
#  Inheritance is always public.
#  Support single inheritance from other classes and multiple inheritance from interfaces.
#  Interfaces cannot inherit from classes or structs.
#  Structs cannot inherit from other structs or classes, but can inherit from interfaces.

#  Methods in an interface that have default bodies are implicitly virtual even if 'virtual' is not specified.
#   The first class inheriting these methods does not need to override them since they have default bodies.
#   If overridden in the first inheriting class, then 'virtual' does not need to be used. However, if not used, then the later subclasses cannot continue overriding these methods unless 'virtual' is specified.
#   'override' cannot also be specified for these methods in the first inheriting class. However, later subclasses must use the 'override' if they are declared as 'virtual' in the first deriving class and later subclasses can simply keep using 'override'.
#  Methods in interfaces that do not have default bodies (declarations only) are implicitly abstract even if the 'abstract' is not specified.
#   The first class inheriting these methods must override them since they do not have default bodies.
#   If overridden in the first inheriting class, then 'virtual' does not need to be used. However, if not used, then the later subclasses cannot continue overriding these methods unless 'virtual' is specified.
#   'override' cannot also be specified for these methods in the first inheriting class. However, later subclasses must use the 'override' if they are declared as 'virtual' in the first deriving class and later subclasses can simply keep using 'override'.
#  Therefore, classes that inherit from interfaces have two options:
#    Either they override the methods, which means that we cannot make them static or they do not override the methods from the interface as long as these methods have a default implementation in the interface.
#    However, this default implementation can be static, and if it is, then it cannot be overridden.
#  So, the best way to deal with this is to ignore these methods in the first inheriting class and only consider methods with the default implementation in the interface itself.
#
# Other cases where a class/struct is inheriting from another class/struct, then the keywords 'virtual' and 'abstract' must be specified in the base class/struct.
#  and the keyword 'override' must be specified in the child class/struct. Therefore, all of these 3 cases cannot be static and can be ignored safely.
#
#  Methods that are have static and properties are ignored from analysis.
# 

import argparse
import os
import sys
import time

from src import statica_agent

def main():
    start_time = time.perf_counter()
    parser = argparse.ArgumentParser(description="Statica: A tool for detecting stateless instance (non-static) methods in C# systems")
    
    parser.add_argument("input_file_path", help="stereotypes and metadata generated by Stereocode (CSV format)")
    parser.add_argument("--output_file_path", default="output.csv", help="Statica results output file name (default: output.csv)")

    args = parser.parse_args()
    
    if not os.path.exists(args.input_file_path):
        print(f"Error: File not found: {args.input_file_path}")
        sys.exit(1)

    output_file_path = args.output_file_path
    if output_file_path == "output.csv":
        project_root = os.path.dirname(os.path.abspath(__file__))
        output_file_path = os.path.join(project_root, args.output_file_path)
    
    print("\n--- Initializing Statica Agent ---")
    
    agent = statica_agent()
    
    initial_state = {
        "input_file_path": args.input_file_path,
        "output_file_path": output_file_path,
    }

    print("--- Running Workflow ---")
    agent.invoke(initial_state)

    end_time = time.perf_counter()
    execution_time = end_time - start_time
    print(f"\n--- Total Execution Time: {execution_time:.2f} seconds ---")

if __name__ == "__main__":
    main()
