# C# Inheritance Rules:
#
#  Inheritance is always public and this cannot be changed.
#  Interfaces cannot inherit from classes or structs, but can inherit from other interfaces.
#  Structs cannot inherit from other structs or classes, but can inherit from interfaces.
#  Classes can inherit from ONE base class and MULTIPLE interfaces (Classes CANNOT inherit from structs).
#
#  Methods in an interface that have default bodies are implicitly virtual even if 'virtual' is not specified.
#   The first class/struct implementing these methods does not need to provide a body since they have default bodies.
#   If implemented in the first class/struct, 'virtual' does not need to be used. However, if not used, later subclasses cannot override these methods.
#   The 'override' keyword CANNOT be used when first implementing these methods as C# consider it implementing (despite having a default body) rather than overriding.
#
#  Methods in interfaces that do not have default bodies (declarations only) are implicitly abstract even if 'abstract' is not specified.
#   The first class/struct inheriting these interfaces MUST implement them.
#   When implementing them, the 'override' keyword CANNOT be used. 
#   If the implementing class wants to allow its subclasses to override the method, it must mark it as 'virtual'. 
#
#  Therefore, classes/structs that inherit from interfaces have two options:
#   1. They implement the methods (no 'override' keyword used), meaning they are tied to the interface and cannot be static.
#   2. They rely on the default implementation provided by the interface (which is always an instance method, never static).
#   (Note: While interfaces can contain explicit 'static' methods, those are not inherited by the implementing class/struct).
#
# STATICA:
# Other cases where a class is inheriting from another base class, the keywords 'virtual' or 'abstract' must be specified in the base class, and the keyword 'override' MUST be specified in the child class. 
# Because 'override' is strictly required for base-class inheritance, these methods can be caught deterministically and ignored safely without an LLM.
# Interface implementations lack the 'override' keyword,  which is exactly why the LLM is required for them.
#

import argparse
import os
import sys
import time

from src import statica_agent

def main():
    start_time = time.perf_counter()
    parser = argparse.ArgumentParser(description="Statica: A tool for detecting stateless instance (non-static) methods in C# systems")
    
    parser.add_argument("input_file_path", help="stereotypes and metadata generated by Stereocode (CSV format)")
    parser.add_argument("--output_file_path", default="output.csv", help="Statica results output file name (default: output.csv)")

    args = parser.parse_args()
    
    if not os.path.exists(args.input_file_path):
        print(f"Error: File not found: {args.input_file_path}")
        sys.exit(1)

    output_file_path = args.output_file_path
    if output_file_path == "output.csv":
        project_root = os.path.dirname(os.path.abspath(__file__))
        output_file_path = os.path.join(project_root, args.output_file_path)
    
    print("\n--- Initializing Statica Agent ---")
    
    agent = statica_agent()
    
    initial_state = {
        "input_file_path": args.input_file_path,
        "output_file_path": output_file_path,
    }

    print("--- Running Workflow ---")
    agent.invoke(initial_state)

    end_time = time.perf_counter()
    execution_time = end_time - start_time
    print(f"\n--- Total Execution Time: {execution_time:.2f} seconds ---")

if __name__ == "__main__":
    main()
